package cn.gao.test;// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;

import java.io.IOException;
import java.util.*;
import java.util.logging.ConsoleHandler;
import java.util.logging.Handler;
import java.util.logging.Level;
import java.util.logging.Logger;

public class GenJinLuRu {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    List<Student> studentList;
    public static Logger logger = Logger.getLogger(GenJinLuRu.class.toString());

    static {
        Handler console = new ConsoleHandler();
        console.setLevel(Level.INFO);
        logger.addHandler(console);
    }




    @Before
    public void setUp() throws IOException {
        System.setProperty("webdriver.chrome.driver", "C:\\Program Files\\Google\\Chrome\\Application\\chromedriver.exe");
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
        ReadExecl readExecl = new ReadExecl();
        studentList =readExecl.readTest();
        Map<String,String> result = new NetWorkUtil().getNetworkDownUp();
        System.out.println(result.get("rxPercent"));
        System.out.println(result.get("txPercent"));
    }

    @After
    public void tearDown() {
        //driver.quit();

    }

    @Test
    public void testInput() throws InterruptedException {
        driver.get("http://ke.ruandy.com/edu/index/login/login.html");
        driver.manage().window().setSize(new Dimension(1050, 840));
        driver.findElement(By.id("number")).click();
        driver.findElement(By.id("number")).sendKeys("13476681696");
        driver.findElement(By.id("password")).click();
        driver.findElement(By.id("password")).sendKeys("123456");
        driver.findElement(By.cssSelector(".btn")).click();
        Thread.sleep(12000);
        WebElement element1 = driver.findElement(By.linkText("下次一定"));
        while(element1==null){
            Thread.sleep(10000);
        }
        driver.findElement(By.linkText("下次一定")).click();
        driver.findElement(By.linkText("讲师工作台")).click();
        driver.findElement(By.linkText("学员列表")).click();
        driver.findElement(By.name("sample_1_length")).click();
        {
            WebElement dropdown = driver.findElement(By.name("sample_1_length"));
            dropdown.findElement(By.xpath("//*[@id=\"sample_1_length\"]/label/select/option[3]")).click();
            Thread.sleep(10000);
        }
        List nameList = new ArrayList();
        //driver.findElement(By.cssSelector(".odd td:nth-child(2)"));
        List<WebElement> list = driver.findElements(By.cssSelector(".odd td:nth-child(2) a"));
        System.out.println("页面查找到得数据"+list.size());
     /*   for (WebElement webElement : list) {
            nameList.add(webElement.getText());

        }*/

        Iterator iterator = studentList.iterator();
        do {
            Student student = (Student)iterator.next();
            for (WebElement webElement : list) {
                if (student.getName().trim().equals(webElement.getText().trim())) {
                    try {
                        Thread.sleep(2000);
                        WebElement tr= webElement.findElement(By.xpath(".//..//.."));
                        tr.findElement(By.xpath(".//td[last()]/div")).click();
                        Thread.sleep(2000);
                        driver.findElement(By.linkText("跟进记录")).click();
                        {
                            WebElement element = driver.findElement(By.tagName("body"));
                            Actions builder = new Actions(driver);
                            builder.moveToElement(element, 0, 0).perform();
                        }
                        Thread.sleep(3000);
                        driver.findElement(By.cssSelector(".span5 .radio:nth-child(2) > #uniform-undefined #uniform-undefined > span")).click();
                        Thread.sleep(3000);
                        driver.findElement(By.name("myModal1_content")).click();
                        Thread.sleep(2000);
                        driver.findElement(By.name("myModal1_content")).sendKeys(student.getInformation());
                        Thread.sleep(2000);
                        driver.findElement(By.cssSelector("#myModal1 .btn-success")).click();
                        //driver.findElement(By.cssSelector("#myModal1 .btn-danger")).click();
                        Thread.sleep(2000);
                        System.out.println(student.getName()+":::::::"+(student.getInformation()));
                        System.out.println(studentList.size());
                        iterator.remove();
                        Thread.sleep(2000);
                        //成功跟进后，将该条数从集合中去除掉之后
                    }catch (Exception e){
                        //产生异常都捕获记录到日志文件中
                        e.printStackTrace();
                    }
                }
            }
        }while (iterator.hasNext());
    }
}
